# Generated by Django 2.1 on 2020-11-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201025_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='color',
            field=models.CharField(default='grey', max_length=32),
        ),
    ]
